# -*- coding: utf-8 -*-
"""session4_0902factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnAveQ7LcnR5oh9CQ_Kaz8CoYIy7D9vs
"""

n = 5
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)