# -*- coding: utf-8 -*-
"""session4_0902.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnAveQ7LcnR5oh9CQ_Kaz8CoYIy7D9vs
"""

class Student:
    def __init__(self):
        self.name = "Rahul"
        self.roll = 101
        self.marks = 87.5


s1 = Student()

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", s1.marks)

n = 5
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)