# -*- coding: utf-8 -*-
"""session05_0902.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnRkkYH7fpD9VgRNFUuoSGEygpJcq8XL
"""

n = int(input("Enter a number: "))

if n <= 1:
    print("Not a Prime Number")
else:
    for i in range(2, n):
        if n % i == 0:
            print("Not a Prime Number")
            break
    else:
        print("Prime Number")